config/routes.rb
Rails.application.routes.draw do

  root 'items#home'

  devise_for :users, controllers: { registrations: 'users/registrations' }

  get '/dashboard', to: 'items#dashboard'

  get '/plans', to: 'items#plans'

  put '/request_item/:id', to: 'item_requests#create',
                           as: :request_item

  resources :items

  resources :conversations do
    resources :messages
  end


  post 'item_requests', to: 'item_requests#create'
  patch 'update_item_requests', to: 'item_requests#update'

end

app/views/partials/_basic_form.html.erb
<h2>Basic Account</h2>

<%= form_for(resource, as: resource_name, url: registration_path(resource_name)) do |f| %>
<%= devise_error_messages! %>

<%= hidden_field_tag 'plan', params[:plan] %>

<div class="field form-group">
  <%= f.label :username %><br />
  <%= f.text_field :username, autofocus: true, class: 'form-control' %>
</div>

<div class="field form-group">
  <%= f.label :password %>
  <% if @minimum_password_length %>
  <em>(<%= @minimum_password_length %> characters minimum)</em>
  <% end %><br />
  <%= f.password_field :password, autocomplete: "off", class: 'form-control' %>
</div>

<div class="field form-group">
  <%= f.label :password_confirmation %><br />
  <%= f.password_field :password_confirmation, autocomplete: "off", class: 'form-control' %>
</div>

<div class="field form-group">
  <span class="input-group-addon">
    <%= f.label 'Informant' %>
    <%= f.radio_button :is_informant, true, checked: true %>
    <%= f.label 'Journalist' %>
    <%= f.radio_button :is_informant, false, checked: false %>
  </span>
</div>

<div class="actions form-group">
  <%= f.submit "Sign up", class: 'btn btn-filled btn-primary' %>
</div>
<% end %>

app/views/partials/_flash_messages.html.erb
<div class="row">
  <div class="col-xs-6 col-xs-offset-3">
    <% flash.each do |type, message| %>
      <div class="alert <%= bootstrap_class_for(type) %>">
        <%= message %>
      </div>
    <% end %>
  </div>
</div>

app/views/partials/_informant_table.html.erb
<div class="table">

  <div class="table-row header green">
    <div class="cell text-center">#</div>
    <div class="cell">Uploaded</div>
    <div class="cell">Status</div>
    <div class="cell">Requesters</div>
    <div class="cell">Approve</div>
  </div>


  <% @items.each do |item| %>
    <div class="table-row">
      <div class="cell text-center">
        <%= item.id %>
      </div>

      <div class="cell">
        <%= link_to item.title, item_path(item) %>
      </div>


      <% if item.item_requests.any? %>
        <% if item.item_requests.find_by(approved: true) %>
        <div class="cell">Approved</div>
        <% else %>
        <div class="cell">Requested</div>
        <% end %>

        <div class="cell">
          <%= form_for :item_request, url: update_item_requests_path, method: :patch do |f| %>

            <!-- Find if any item_requests have been approved -->
            <% if item.item_requests.any? { |r| r.approved } %>
            <!-- If there are, find that record and only show that one so that you can't approve multiple -->
            <%= item.item_requests.where(approved: true).first.user.username %>
            <%= f.hidden_field :user_id, value: item.item_requests.where(approved: true).first.user.id %>
            <% else %>
            <!-- If none are approved, choose which you would like to approve -->
            <%= f.select :user_id, item.requesters.map { |requester| [requester.username, requester.id] }, class: 'form-control' %>
            <% end %>
            <%= f.hidden_field :item_id, value: item.id %>
        </div>

        <div class="cell approval-cell">
            <% if item.item_requests.any? { |r| r.approved } %>
              <%= f.submit 'Disapprove', class: 'btn btn-primary btn-filled' %>
            <% else %>
              <%= f.submit 'Approve', class: 'btn btn-primary btn-filled' %>
            <% end %>
          <% end %>
        </div>

      <% else %>
        <div class="cell">Posted</div>
        <div class="cell"></div>
        <div class="cell"></div>
      <% end %>
    </div>
  <% end %>

</div>

<% if @items.count <= 0 %>
    <div class="well text-center">
      <i>You have no items uploaded.</i>
    </div>
  <% end %>

app/views/partials/_journalist_table.html.erb
<div class="table">
  <div class="table-row header green">
    <div class="cell text-center">#</div>
    <div class="cell">Requested</div>
    <div class="cell">Status</div>
    <div class="cell">Request date</div>
  </div>



  <% current_user.requested_items.each do |item| %>
    <div class="table-row">
      <% if item.item_requests.any? %>
        <div class="cell text-center"><%= item.id %></div>
        <div class="cell"><%= link_to item.title, item_path(item) %></div>
        <% if item.item_requests.find_by(user_id: current_user.id, approved: true) %>
        <div class="cell">Approved</div>
        <% elsif !item.item_requests.find_by(approved: true) %>
        <div class="cell">Requested</div>
        <% else %>
        <div class="cell">Ignored</div>
        <% end %>
        <div class="cell"><%= item.created_at.to_date %></div>
      <% end %>
    </div>
  <% end %>
</div>


<div class="table">
  <div class="table-row header green">
    <div class="cell">Total Requests</div>
    <div class="cell">Total Approvals</div>
  </div>

  <div class="table-row">
  <% requests = [] %>
  <% approvals = [] %>
  <% current_user.requested_items.each do |item| %>
    <% requests << item %>
    <% if item.item_requests.find_by(approved: true) %>
      <% approvals << item %>
    <% end %>
  <% end %>
     <div class="cell"><%= requests.count %></div>
    <div class="cell"><%= approvals.count %></div>
  </div>

</div>

app/views/partials/_nav.html.erb
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Secret Source', root_path, class: 'navbar-brand' %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to 'Home', root_path %></li>
        <li><%= link_to 'Sources', items_path %></li>
        <li><%= link_to 'Inbox', conversations_path %></li>
        <li><%= link_to 'Dashboard', dashboard_path %></li>

        <% if user_signed_in? %>
          <li><%= link_to "Sign out", destroy_user_session_path, method: :delete, class: 'btn btn-primary btn-filled btn-xs' %></li>
        <% else %>
          <li><%= link_to 'Sign in', new_user_session_path, class: 'btn btn-primary btn-filled btn-xs' %></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/partials/_pro_form.html.erb
<h2>Premium Account</h2>

<%= form_for(resource, as: resource_name, url: registration_path(resource_name), html: {id: 'proForm'})   do |f| %>
<%= devise_error_messages! %>

<%= hidden_field_tag 'plan', params[:plan] %>

<div class="field form-group">
  <%= f.label :username %><br />
  <%= f.text_field :username, autofocus: true, class: 'form-control' %>
</div>

<div class="field form-group">
  <%= f.label :password %>
  <% if @minimum_password_length %>
  <em>(<%= @minimum_password_length %> characters minimum)</em>
  <% end %><br />
  <%= f.password_field :password, autocomplete: "off", class: 'form-control' %>
</div>

<div class="field form-group">
  <%= f.label :password_confirmation %><br />
  <%= f.password_field :password_confirmation, autocomplete: "off", class: 'form-control' %>
</div>

<div class="field form-group">
  <span class="input-group-addon">
    <%= f.label 'Informant' %>
    <%= f.radio_button :is_informant, true, checked: true, class: 'btn btn-primary' %>
    <%= f.label 'Journalist' %>
    <%= f.radio_button :is_informant, false, checked: false, class: 'btn btn-primary' %>
  </span>
</div>

<div class="field form-group">
    <%= label_tag :card_number, "Credit Card Number" %>
    <%= text_field_tag :card_number, nil, name: nil, class: "form-control" %>
  </div>
  <div class="field form-group">
    <%= label_tag :card_code, "Security Code (CVV)" %>
    <%= text_field_tag :card_code, nil, name: nil, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= label_tag :card_month, "Card Expiration" %>
    <%= select_month nil, { add_month_numbers: true }, { name: nil, id: "card_month" } %>
    <%= select_year nil, { start_year: Date.today.year, end_year: Date.today.year+15 }, { name: nil, id: "card_year" } %>
  </div>

<div class="actions form-group">
  <%= f.submit "Sign up", class: 'btn btn-filled btn-primary', id: 'form-sign-up-btn' %>
</div>
<% end %>